# Wrapper around embedded RISCV VM
#
# Copyright (C) 2026 Timofey Titovets <nefelim4ag@gmail.com>
#
# This file may be distributed under the terms of the GNU GPLv3 license.

import os
import mcu
import logging
import subprocess

BACKGROUND_PRIORITY_CLOCK = 0x7fffffff00000000

class EmbeddedVM:
    def __init__(self, mcu, cfile, macro_flags={}):
        self.mcu = mcu
        self.printer = mcu.get_printer()
        self.cmd_queue = self.mcu.alloc_command_queue()
        self.dir = os.path.dirname(os.path.abspath(__file__))
        # Compile something
        toolchains = [ "unknown-elf", "linux-gnu" ]
        self.CC      = "riscv64-%s-gcc"
        self.OBJCOPY = "riscv64-%s-objcopy"
        self.NM      = "riscv64-%s-nm"
        self.CFLAGS  = "-O2 -march=rv32e -mabi=ilp32e -ffreestanding " \
                       "-nostdlib -fPIE -Wvla -Werror=vla " \
                       "-Werror=stack-usage=256 " \
                       "-ffunction-sections -fdata-sections " \
                       "-I%s" % self.dir
        try:
            tool = self.CC % toolchains[0]
            self._run(["which", tool])
            self.CC = self.CC % toolchains[0]
            self.OBJCOPY = self.OBJCOPY % toolchains[0]
            self.NM = self.NM % toolchains[0]
        except self.printer.command_error:
            tool = self.CC % toolchains[1]
            self._run(["which", tool])
            self.CC = self.CC % toolchains[1]
            self.OBJCOPY = self.OBJCOPY % toolchains[1]
            self.NM = self.NM % toolchains[1]

        for k, v in macro_flags.items():
            flag = " -D%s=%s" % (k.upper(), v)
            self.CFLAGS += flag
        self.cfile = cfile
        self.binfile = None
        self.binfile_size = 0
        self._evm_update_cmd = None
        self._evm_send = None
        self._evm_query = None

        # Configure MCU objects
        self._oid = self.mcu.create_oid()
        self.mcu.register_config_callback(self._build_config)
        self.printer.register_event_handler("klippy:connect",
                                            self.handle_connect)

    def get_oid(self):
        return self._oid

    def _run(self, cmd):
        cmd = " ".join(cmd)
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        if r.returncode != 0:
            logging.error(r.stderr)
            raise self.printer.command_error("Command failed (exit %d})" %
                                             r.returncode)
        return r.stdout

    def read_bytes(self, path):
        with open(path, "rb") as f:
            return f.read()

    def _generate_header(self):
        dir = self.dir
        fw_calls = self.mcu.get_enumerations().get("fw_calls", {})
        header_template = "/* DO NOT EDIT THIS AUTOGENERATED FILE */\n" \
                          "#include \"uapi.h\"\n\n"
        evm_flags = self.mcu.get_enumerations().get("evm_flags", {})
        for k, v in evm_flags.items():
            header_template += "#define %s %s\n" % (k, v)
        anon_struct = []
        for raw_def, id in fw_calls.items():
            params = raw_def.split("|")
            ret_type = params.pop(0)
            type_def = ret_type.strip("*").strip()
            if "struct" in type_def and type_def not in anon_struct:
                    anon_struct.append(type_def)
                    header_template += "%s;\n" % type_def
            fn_name = params.pop(0)
            args = params
            args_num = len(args)
            arg_names = [str(id)]
            for arg in args:
                arg_parts = arg.split(' ')
                type_def = " ".join(arg_parts[:-1])
                arg_names.append(arg_parts[-1].strip("*"))
                if "struct " in type_def and type_def not in anon_struct:
                    anon_struct.append(type_def)
                    header_template += "%s;\n" % type_def
            header_template += '%s %s(%s) {\n' % (
                ret_type, fn_name, ", ".join(args))
            ecall = 'RISC_V_EVM_CALL_N%d(%s)' % (
                args_num, ", ".join(arg_names))
            if ret_type != 'void':
                header_template += '    return (%s) %s;\n}\n' % (
                    ret_type, ecall)
            else:
                header_template += '    %s;\n}\n' % ecall
            header_template += '\n'
        with open("%s/uapi-gen.h" % dir, "w") as f:
            f.write(header_template)

    def _compile(self):
        dir = self.dir
        objfile = "%s.o" % (self.cfile)
        self._run([self.CC, self.CFLAGS, "-c", "-o", objfile,
                   self.cfile])
        elffile = "%s.elf" % self.cfile
        self._run([self.CC, self.CFLAGS,
                   "-T %s/rv32e.ld -static -Wl,--build-id=none " % dir,
                   "-Wl,--gc-sections ",
                   "-o ", elffile, objfile])
        binfile = "%s.bin" % self.cfile
        self._run([self.OBJCOPY, "-O binary", elffile, binfile])
        self.binfile = binfile
        symbol_list = self._run([self.NM, "--radix=d", elffile])
        entry_points = {}
        for line in symbol_list.split('\n'):
            if not line:
                continue
            offset, symbol_type, name = line.split(' ')
            if symbol_type != 'T':
                continue
            entry_points[name] = int(offset)
        return entry_points

    def _build_config(self):
        self._generate_header()
        symbols = self._compile()
        cmd_offset = symbols.get("command", 0)
        if cmd_offset != 0:
            self.printer.command_error("evm command function must be first")
        task_offset = symbols.get("task", 0)
        binfile_size = len(self.read_bytes(self.binfile))
        self.mcu.add_config_cmd("config_evm oid=%d data_size=%d "
                                "task_offset=%d evm_mode=%s" % (
                                self._oid, binfile_size, task_offset,
                                'mode_command'))
        # Lookup commands
        self._evm_update_cmd = self.mcu.lookup_command(
            "evm_update oid=%c pos=%hu data=%*s",
            cq=self.cmd_queue)
        self._evm_send = self.mcu.lookup_command(
            "evm_send oid=%c data=%*s", cq=self.cmd_queue)
        self._evm_query = self.mcu.lookup_command(
            "evm_query oid=%c rest_ticks=%u", cq=self.cmd_queue)

    def handle_connect(self):
        byte_code = self.read_bytes(self.binfile)
        ucmd = self._evm_update_cmd.send
        chunk_size = 48
        for pos in range(0, len(byte_code), chunk_size):
            ucmd([self._oid, pos, byte_code[pos:pos+chunk_size]],
                 reqclock=BACKGROUND_PRIORITY_CLOCK)
        if self.printer.get_start_args().get('debugoutput') is not None:
            return
    def send(self, data):
        self._evm_send.send([self._oid, bytes(data)])

    def query(self, rest_ticks):
        self._evm_query.send([self._oid, rest_ticks])
